---
development:
  cloud_name: dg5a0q8vf
  api_key: '391922162427883'
  api_secret: BQsgk8rLYifC6wV7wOohFuE8Gqk
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dg5a0q8vf
  api_key: '391922162427883'
  api_secret: BQsgk8rLYifC6wV7wOohFuE8Gqk
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dg5a0q8vf
  api_key: '391922162427883'
  api_secret: BQsgk8rLYifC6wV7wOohFuE8Gqk
  enhance_image_tag: true
  static_file_support: false
